unified rollup/unrollup test tree

diff --git a/test/regression/rollup_tree.sh.in b/test/regression/rollup_tree.sh.in
--- a/test/regression/rollup_tree.sh.in
+++ b/test/regression/rollup_tree.sh.in
@@ -62,41 +62,93 @@
 
 
 set -e
-source @CMAKE_CURRENT_BINARY_DIR@/rollup_tree.sh
+source @CMAKE_CURRENT_BINARY_DIR@/setup.sh 0
 
-cleanup() {
-    rollup_tree_cleanup
+TMP="tmp"
+
+rollup_tree_cleanup() {
+    rm -rf "${TMP}"
 }
 
-cleanup_exit() {
-    cleanup
-    setup_cleanup
+trap rollup_tree_cleanup EXIT
+
+rollup_tree_cleanup
+
+# Level 0                 prefix/
+#       Total 1 directory
+#
+# Level 1  007 o+rx | ugo 777   | ug 770    | 700 u
+#          fail     | success   | fail      | fail
+#
+#       Total 4 directories; 1 will roll up
+#
+# Level 2
+#          o+rx 007 | o+rx 007  | o+rx 007  | o+rx 007
+#          ugo  777 | ugo  777  | ugo  777  | ugo  777
+#          ug   770 | ug   770  | ug   770  | ug   770
+#          u    700 | u    700  | u    700  | u    700
+#
+#       Total 4 x 4 = 16 directories
+#       All directories should roll up
+#
+# Level 3
+#       Total 4 x 4 x      3      = 48 directories
+#       Total 4 x 4 x (1 + 2 + 3) = 96 files
+#
+# Total     = 1 + 4 + 16 + 48 = 69 directories
+# Rolled up =     1 +  4 + 48 = 53 directories (52 subdirectories)
+# Remaining = 1 + 3 + 12      = 16 directories
+#
+
+level3() {
+    parent="$1"
+    perms="$2"
+    count="$3"
+
+    dir="${parent}/dir${count}"
+
+    mkdir -m "${perms}" "${dir}"
+    for (( i = 1; i <= count; i++ ))
+    do
+        filename="${dir}/file${i}"
+        touch "${filename}"
+    done
 }
 
-trap cleanup_exit EXIT
+mkdir "${TMP}"                                    # Level 1
 
-cleanup
+mkdir -m 007 "${TMP}/o+rx"                        # Level 2 007
+level3 "${TMP}/o+rx" 777 1                        # Level 3 777 - 1 file
+level3 "${TMP}/o+rx" 077 2                        # Level 3 077 - 2 files
+level3 "${TMP}/o+rx" 007 3                        # Level 3 007 - 3 files
 
-OUTPUT="unrollup.out"
+mkdir -m 777 "${TMP}/ugo"                         # Level 2 777
+level3 "${TMP}/ugo" 577 1                         # Level 3 577 - 1 file
+level3 "${TMP}/ugo" 757 2                         # Level 3 757 - 2 files
+level3 "${TMP}/ugo" 775 3                         # Level 3 775 - 3 files
 
-(
-# generate the index
-run_no_sort "${GUFI_DIR2INDEX} -x \"${SRCDIR}\" \"${INDEXTARGET}\""
+mkdir -m 770 "${TMP}/ug"                          # Level 2 770
+level3 "${TMP}/ug" 777 1                          # Level 3 577 - 1 file
+level3 "${TMP}/ug" 770 2                          # Level 3 757 - 2 files
+level3 "${TMP}/ug" 750 3                          # Level 3 775 - 3 files
 
-# roll up the index
-echo "$ ${ROLLUP} \"${INDEXROOT}\"" | replace
-${ROLLUP} "${INDEXROOT}" | replace 2> /dev/null
-echo
+mkdir -m 700 "${TMP}/u"                           # Level 2 700
+level3 "${TMP}/u" 777 1                           # Level 3 777 - 1 file
+level3 "${TMP}/u" 700 2                           # Level 3 700 - 2 files
+level3 "${TMP}/u" 500 3                           # Level 3 500 - 3 files
 
-echo "# rolled up directories should have rows in pentries_rollup"
-run_sort "${GUFI_QUERY} -d \" \" -S \"SELECT rpath(name, rollupscore), rollupscore, (SELECT COUNT(*) FROM pentries_rollup) FROM summary WHERE isroot == 1;\" \"${INDEXROOT}\""
+mkdir -m 777 "${SRCDIR}"                          # Level 0
 
-# unroll up the index
-run_no_sort "${UNROLLUP} \"${INDEXROOT}\""
+cp --preserve=xattr -R "${TMP}" "${SRCDIR}/o+rx"  # Level 1
+chmod 007 "${SRCDIR}/o+rx"
 
-echo "# level, COUNT(entries), COUNT(pentries_rollup), directory"
-run_no_sort "${GUFI_QUERY} -d \" \" -S \"SELECT level(), (SELECT COUNT(*) FROM entries), (SELECT COUNT(*) FROM pentries_rollup), rpath(name, rollupscore) AS fullpath FROM summary ORDER BY fullpath ASC\" \"${INDEXROOT}\"" | @SORT@ -k4 | @TAIL@ -n +2
-) | @SED@ "s/${SRCDIR//\//\\/}\\///g" | remove_indexing_time | @TEE@ "${OUTPUT}"
+cp --preserve=xattr -R "${TMP}" "${SRCDIR}/ugo"   # Level 1
+chmod 777 "${SRCDIR}/ugo"
 
-@DIFF@ @CMAKE_CURRENT_BINARY_DIR@/unrollup.expected "${OUTPUT}"
-rm "${OUTPUT}"
+cp --preserve=xattr -R "${TMP}" "${SRCDIR}/ug"    # Level 1
+chmod 770 "${SRCDIR}/ug"
+
+cp --preserve=xattr -R "${TMP}" "${SRCDIR}/u"     # Level 1
+chmod 700 "${SRCDIR}/u"
+
+rm -r "${TMP}"
