regression test artifacts
artifacts are now placed into TEST_WORKING_DIRECTORY/<name>-<unix timestamp>
    output is now placed in TEST_WORKING_DIRECTORY/<name>-<unix timestamp>/out
link TEST_WORKING_DIRECTORY/<name> is created to point to the latest output
if a regression tests passes
    the artifacts are deleted
    the link reverts to pointing to an older artifact or is deleted

diff --git a/test/regression/setup.sh.in b/test/regression/setup.sh.in
--- a/test/regression/setup.sh.in
+++ b/test/regression/setup.sh.in
@@ -65,26 +65,43 @@
 
 set -e
 
-if [[ "$#" -ne "1" ]]
+if [[ "$#" -ne "2" ]]
 then
-    echo "Syntax: $0 <generate index>" 1>&2
+    echo "Syntax: $0 <test name> <generate index>" 1>&2
     exit 1
 fi
 
-GENERATE_INDEX="$1"
+TEST_NAME="$1"
+GENERATE_INDEX="$2"
 
-SRCDIR="prefix"
+TEST_WORKING_DIRECTORY="@TEST_WORKING_DIRECTORY@"
+
+if [[ -z "${TEST_WORKING_DIRECTORY}" ]]
+then
+    TEST_WORKING_DIRECTORY="$(pwd)"
+fi
+
+# create a subdirectory to place individual tests into
+TEST_DIR="${TEST_WORKING_DIRECTORY}/${TEST_NAME}-$(date +%s)"
+TEST_DIR_LATEST="${TEST_WORKING_DIRECTORY}/${TEST_NAME}"
+
+# common test output file name
+# shellcheck disable=SC2034
+TEST_OUTPUT="out"
+
+SRCDIR="${TEST_DIR}/prefix"
 BASENAME="$(basename ${SRCDIR})"
 THREADS=2
 
 TRACE="trace"
-BADTRACE="badtrace"
 TRACES=()
 for (( i = 0; i < THREADS; i++ ));
 do
     TRACES+=("${TRACE}.${i}")
 done
 DELIM="|"
+# shellcheck disable=SC2034
+BADTRACE="badtrace"
 # shellcheck disable=SC2034
 BADDELIM="?"
 
@@ -111,14 +128,38 @@ TEST_GROUP_ID="${TEST_USER_ID}"
 # shellcheck disable=SC2034
 TEST_GROUP_NAME="group"
 
-# always clean up
+# call at end of each test that sources this file
+# clean up if there are no errors
 setup_cleanup() {
-    rm -rf "${CONFIG}" "${SRCDIR}" "${TRACE}" "${TRACES[@]}" "${BADTRACE}" "${SEARCH}" "${SKIP}"
+    if [[ -d "${TEST_WORKING_DIRECTORY}" ]]
+    then
+        # remove existing output dir (should never exist) and link to latest output
+        rm -rf "${TEST_DIR}" "${TEST_DIR_LATEST}"
+
+        # find latest output directory
+        PREVIOUS=$(find "${TEST_WORKING_DIRECTORY}" -mindepth 1 -maxdepth 1 -name "${TEST_NAME}-*" -type d | sort -nr | head -n 1)
+
+        # if one exists, create a link to it
+        if [[ -n "${PREVIOUS}" ]]
+        then
+            ln -sf "${PREVIOUS}" "${TEST_DIR_LATEST}"
+        fi
+    fi
 }
 
-trap setup_cleanup EXIT
-
+# always clean up existing data
 setup_cleanup
+
+mkdir -p "${TEST_DIR}"
+
+# link to new test output
+#
+# at end of test, will either point to current output
+# or be changed to previous test output if it exists
+rm -f "${TEST_DIR_LATEST}"               # need this because ln -f is not replacing
+ln -s "${TEST_DIR}" "${TEST_DIR_LATEST}"
+
+cd "${TEST_DIR}"
 
 umask 002
 export TZ=UTC
@@ -232,13 +273,16 @@ replace() {
     /-e                          compress work items/d;
     /Started [0-9]* threads. Successfully completed [0-9]* threads./d;
 
-    s/${INDEXROOT//\//\\/}/${SRCDIR//\//\\/}/g;
+    s/${TEST_DIR//\//\\/}\\///g;
+    s/${INDEXROOT//\//\\/}/${BASENAME//\//\\/}/g;
     s/${CONFIG//\//\\/}/\\/etc\\/GUFI\\/config/g;
     s/${PWD//\//\\/}\\///g;
 
     s/${AWK//\//\\/}/awk/g;
     s/${DIFF//\//\\/}/diff/g;
     s/${GREP//\//\\/}/grep/g;
+
+    /getfattr: Removing leading '\/' from absolute path names/d;
 
     s/[[:space:]]*$//g;
     "
@@ -250,31 +294,31 @@ replace_argparse() {
 }
 
 run_sort() {
-    echo "$" "$@"                             |& replace
+    echo "$" "$@"                                  | replace
     # shellcheck disable=SC2294
-    eval "${GUFI_PYTHON_TEST_COVERAGE}" "$@"  |& replace | sort
+    eval "${GUFI_PYTHON_TEST_COVERAGE}" "$@"  2>&1 | replace | sort
     echo
 }
 
 run_no_sort() {
-    echo "$" "$@"                             |& replace
+    echo "$" "$@"                                  | replace
     # shellcheck disable=SC2294
-    eval "${GUFI_PYTHON_TEST_COVERAGE}" "$@"  |& replace
+    eval "${GUFI_PYTHON_TEST_COVERAGE}" "$@"  2>&1 | replace
     echo
 }
 
 # somewhat force ordering of trace file
 order_tracefile() {
-    @GREP@ -a "^${SRCDIR}${DELIM}"              "$1"
-    @GREP@ -a "^${SRCDIR}/.hidden${DELIM}"      "$1"
-    @GREP@ -a "^${SRCDIR}/1KB${DELIM}"          "$1"
-    @GREP@ -a "^${SRCDIR}/1MB${DELIM}"          "$1"
-    @GREP@ -a "^${SRCDIR}/file_symlink${DELIM}" "$1"
-    @GREP@ -a "^${SRCDIR}/old_file${DELIM}"     "$1"
-    @GREP@ -a "^${SRCDIR}/repeat_name${DELIM}"  "$1"
-    @GREP@ -a "^${SRCDIR}/directory.*${DELIM}"  "$1"
-    @GREP@ -a "^${SRCDIR}/leaf.*${DELIM}"       "$1"
-    @GREP@ -a "^${SRCDIR}/unusual.*${DELIM}"    "$1"
+    @GREP@ -a "^${BASENAME}${DELIM}"              "$1"
+    @GREP@ -a "^${BASENAME}/.hidden${DELIM}"      "$1"
+    @GREP@ -a "^${BASENAME}/1KB${DELIM}"          "$1"
+    @GREP@ -a "^${BASENAME}/1MB${DELIM}"          "$1"
+    @GREP@ -a "^${BASENAME}/file_symlink${DELIM}" "$1"
+    @GREP@ -a "^${BASENAME}/old_file${DELIM}"     "$1"
+    @GREP@ -a "^${BASENAME}/repeat_name${DELIM}"  "$1"
+    @GREP@ -a "^${BASENAME}/directory.*${DELIM}"  "$1"
+    @GREP@ -a "^${BASENAME}/leaf.*${DELIM}"       "$1"
+    @GREP@ -a "^${BASENAME}/unusual.*${DELIM}"    "$1"
 }
 
 remove_indexing_time() {
