simple treediff
prints top-most directory that is different and stops
only handles name mismatches

diff --git a/test/regression/treediff.sh.in b/test/regression/treediff.sh.in
--- a/test/regression/treediff.sh.in
+++ b/test/regression/treediff.sh.in
@@ -1,3 +1,4 @@
+#!/usr/bin/env bash
 # This file is part of GUFI, which is part of MarFS, which is released
 # under the BSD license.
 #
@@ -60,146 +61,38 @@
 
 
 
-cmake_minimum_required(VERSION 3.1.0)
+set -e
+source @CMAKE_CURRENT_BINARY_DIR@/setup.sh 1
 
-# regression test specific files
-set(CORE
-  generatetree.sh
-  os_setfattr.sh
-  setup.sh
-)
+OUTPUT="treediff.out"
 
-foreach(NAME ${CORE})
-  configure_file("${NAME}.in" "${NAME}" @ONLY)
-endforeach()
+(
+run_no_sort "${TREEDIFF} -h"
 
-set(BINARIES
-  gufi_dir2index
-  gufi_dir2trace
-  gufi_trace2index
-  gufi_treesummary
-  gufi_treesummary_all
-  gufi_query
-  gufi_stat_bin
-  querydbs
-)
+echo "# Compare against the same tree"
+run_sort "${TREEDIFF} \"${SEARCH}\" \"${SEARCH}\""
 
-set(PYTHON
-  gufi_find
-  gufi_getfattr
-  gufi_ls
-  gufi_stat
-  gufi_stats
-)
+echo "# Compare against source tree"
+run_sort "${TREEDIFF} \"${SRCDIR}\" \"${INDEXROOT}\""
 
-set(EXAMPLES
-  deluidgidsummaryrecs
-  generategidsummary
-  generateuidsummary
-  gengidsummaryavoidentriesscan
-  genuidsummaryavoidentriesscan
-  groupfilespacehog
-  groupfilespacehogusesummary
-  oldbigfiles
-  userfilespacehog
-  userfilespacehogusesummary
-)
+run_no_sort "mv \"${INDEXROOT}/directory\" \"${INDEXROOT}/new_name\""
 
-set(OTHERS
-  bash_completion
-  split_trace
-  treediff
-)
+echo "# Create directory that will come after \"unusual#? directory ,\" to run cleanup code"
+run_no_sort "mkdir \"${INDEXROOT}/xyz\""
 
-if (ZLIB_FOUND)
-  list(APPEND OTHERS
-    compression
-  )
-endif()
+echo "# Compare different trees"
+run_sort "${TREEDIFF} \"${SRCDIR}\" \"${INDEXROOT}\""
+run_sort "${TREEDIFF} \"${INDEXROOT}\" \"${SRCDIR}\""
 
-if (CMAKE_CXX_COMPILER)
-  list(APPEND OTHERS
-    verifytrace
-    verifytraceintree
-  )
-endif()
+echo "# Not enough levels to show differences"
+run_sort "${TREEDIFF} -z 0 \"${SRCDIR}\" \"${INDEXROOT}\""
 
-# .sh and .expected
-set(SH_AND_EXPECTED
-  ${BINARIES}
-  ${PYTHON}
-  ${EXAMPLES}
-  ${OTHERS}
-)
+echo "# Bad left hand path"
+run_no_sort "${TREEDIFF} \"\" \"${SEARCH}\""
 
-configure_file(gufi_tool.py.in gufi_tool.py)
+echo "# Bad right hand path"
+run_no_sort "${TREEDIFF} \"${SEARCH}\" \"\""
+) | remove_root | tee "${OUTPUT}"
 
-foreach(NAME ${SH_AND_EXPECTED})
-  configure_file("${NAME}.sh.in"    "${NAME}.sh"       @ONLY)
-  configure_file("${NAME}.expected" "${NAME}.expected" COPYONLY)
-
-  add_test(NAME "${NAME}" COMMAND "${CMAKE_CURRENT_BINARY_DIR}/${NAME}.sh"
-    WORKING_DIRECTORY "${TEST_WORKING_DIRECTORY}")
-endforeach()
-
-foreach(NAME ${BINARIES})
-  set_tests_properties("${NAME}" PROPERTIES LABELS "regression;binary")
-endforeach()
-
-foreach(NAME ${EXAMPLES})
-  set_tests_properties("${NAME}" PROPERTIES LABELS "regression;examples")
-endforeach()
-
-foreach(NAME ${OTHERS})
-  set_tests_properties("${NAME}" PROPERTIES LABELS "regression")
-endforeach()
-
-foreach(NAME ${PYTHON})
-  set_tests_properties("${NAME}" PROPERTIES LABELS "regression;python")
-endforeach()
-
-find_program(SUDO sudo)
-if (SUDO)
-  if (APPLE)
-    set(SUDO sudo)
-  endif()
-
-  set(ENABLE_SUDO_TESTS Off CACHE BOOL "Whether or not to enable tests that need sudo")
-  if (ENABLE_SUDO_TESTS)
-    configure_file("rollup_tree.sh.in" "rollup_tree.sh" @ONLY)
-
-    set(SUDO_BINARIES
-      gufi_rollup
-      gufi_unrollup
-    )
-
-    set(SUDO_OTHERS
-      xattrs
-    )
-
-    # .sh and .expected
-    set(NEED_SUDO
-      ${SUDO_BINARIES}
-      ${SUDO_OTHERS}
-    )
-
-    foreach(NAME ${NEED_SUDO})
-      configure_file("${NAME}.sh.in"    "${NAME}.sh"       @ONLY)
-      configure_file("${NAME}.expected" "${NAME}.expected" COPYONLY)
-
-      add_test(NAME "${NAME}" COMMAND ${SUDO} "${CMAKE_CURRENT_BINARY_DIR}/${NAME}.sh"
-        WORKING_DIRECTORY "${TEST_WORKING_DIRECTORY}")
-    endforeach()
-
-    foreach(NAME ${SUDO_BINARIES})
-      set_tests_properties("${NAME}" PROPERTIES LABELS "regression;sudo;binary")
-    endforeach()
-
-    foreach(NAME ${SUDO_OTHERS})
-      set_tests_properties("${NAME}" PROPERTIES LABELS "regression;sudo")
-    endforeach()
-
-  endif()
-else()
-  message(STATUS "sudo executable not found. Not running tests requiring sudo.")
-endif()
+@DIFF@ @CMAKE_CURRENT_BINARY_DIR@/treediff.expected "${OUTPUT}"
+rm "${OUTPUT}"
