macOS updates
cmake configuration now only requires -DCMAKE_OSX_SYSROOT=macosx
    if OpenMP is not found, add -DOpenMP_ROOT="$(brew --prefix libomp)"

create .pkgs
    install for all users not just yourself
    make sure to update DYLD_LIBRARY_PATH after installing

CMakeLists.txt
    replace APPLE OR DARWIN with just DARWIN
    clean up flags

update bundled sqlite-vec
    https://github.com/asg017/sqlite-vec/commit/04d28bd21773981e2d266bbf6aa4efbd011eb4f6

removed CLIENT=Off build

diff --git a/contrib/CI/pkg.sh.in b/contrib/CI/pkg.sh.in
--- a/contrib/CI/pkg.sh.in
+++ b/contrib/CI/pkg.sh.in
@@ -1,3 +1,4 @@
+#!/usr/bin/env bash
 # This file is part of GUFI, which is part of MarFS, which is released
 # under the BSD license.
 #
@@ -60,94 +61,53 @@
 
 
 
-# allow for the test working directory to be moved
-set(TEST_WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}" CACHE PATH "Directory to run tests in")
-execute_process(COMMAND "${CMAKE_COMMAND}" -E make_directory "${TEST_WORKING_DIRECTORY}"
-    COMMAND_ERROR_IS_FATAL ANY)
+set -e
 
-# LeakSanitizer suppressions
-configure_file("lsan.suppressions" "lsan.suppressions" COPYONLY)
+# This script is intended to be run on a clean macOS
+# environment such as the GitHub Actions runner. This
+# script will overwrite existing configuration files.
 
-# ThreadSanitizer suppressions
-configure_file("tsan.suppressions" "tsan.suppressions" COPYONLY)
+# need SQLite3 CLI
+export PATH="@DEP_INSTALL_PREFIX@/sqlite3/bin:${PATH}"
 
-# UndefinedBehaviorSanitizer suppressions
-configure_file("ubsan.suppressions" "ubsan.suppressions" COPYONLY)
+arch="$(uname --machine)"
 
-if (ALLOW_DB_WRITES)
-  # copy test scripts into the test directory within the build directory
-  # list these explicitly to prevent random garbage from getting in
-  foreach(TEST
-      bfwiflat2gufitest
-      dfw2gufitest
-      gufitest.py
-      robinhoodin
-      runbffuse
-      runbfq
-      runbfqforfuse
-      runbfti
-      runbfwi
-      rundfw
-      rungenuidgidsummaryavoidentriesscan
-      rungroupfilespacehog
-      rungroupfilespacehogusesummary
-      runlistschemadb
-      runlisttablesdb
-      runoldbigfiles
-      runquerydbs
-      runuidgidsummary
-      runuidgidummary
-      runuserfilespacehog
-      runuserfilespacehogusesummary
-      runtests
-      )
-    # copy the script into the build directory for easy access
-    configure_file("${TEST}" "${TEST}" @ONLY)
-  endforeach()
+# make the PKGs
+# doing in 2 steps because productbuild likes to
+# merge all components into a monolithic PKG
 
-  set(TESTTAR "${CMAKE_CURRENT_SOURCE_DIR}/testdir.tar")
-  set(TESTDIR "${TEST_WORKING_DIRECTORY}/testdir")
-  set(TESTDST "${TEST_WORKING_DIRECTORY}/gary")
+# make the server PKG
+# requires root to stage @SERVER_CONFIG@ for copying into PKG
+sudo cpack -G productbuild -DCPACK_COMPONENTS_ALL=Server -B "@CMAKE_BINARY_DIR@"
+pkg="GUFI-@CMAKE_PROJECT_VERSION@-Darwin.pkg"
+server="gufi-server-@CMAKE_PROJECT_VERSION@.macOS.${arch}.pkg"
+sudo rm -rf @CPACK_PACKAGING_INSTALL_PREFIX@/etc/GUFI # this assumes GUFI wasn't previously installed
+sudo chown "${USER}" "${pkg}"
+mv "${pkg}" "${server}"
 
-  add_test(
-    NAME gary
-    COMMAND "${CMAKE_CURRENT_BINARY_DIR}/runtests" "${TESTTAR}" "${TESTDIR}" "${TESTDST}"
-    WORKING_DIRECTORY "${TEST_WORKING_DIRECTORY}")
+# make the client PKG
+# requires root to stage @CLIENT_CONFIG@ for copying into PKG
+sudo cpack -G productbuild -DCPACK_COMPONENTS_ALL=Client -B "@CMAKE_BINARY_DIR@"
+pkg="GUFI-@CMAKE_PROJECT_VERSION@-Darwin.pkg"
+client="gufi-client-@CMAKE_PROJECT_VERSION@.macOS.${arch}.pkg"
+sudo rm -rf @CPACK_PACKAGING_INSTALL_PREFIX@/etc/GUFI
+sudo chown "${USER}" "${pkg}"
+mv "${pkg}" "${client}"
 
-  set_property(TEST gary PROPERTY ENVIRONMENT "PATH=${DEP_INSTALL_PREFIX}/sqlite3/bin:$ENV{PATH}")
-  if (DEP_AI AND CYGWIN)
-    # append does not work
-    set_property(TEST gary PROPERTY ENVIRONMENT "PATH=${DEP_INSTALL_PREFIX}/sqlite3/bin:${DEP_INSTALL_PREFIX}/llama.cpp/bin:$ENV{PATH}")
-  endif()
-  set_property(TEST gary APPEND PROPERTY LABELS "manual")
-endif()
+# list the files
+pkgutil --payload-files "${server}" | sort
+pkgutil --payload-files "${client}" | sort
 
-# add regression tests
-if (ALLOW_DB_WRITES) # required to clean up test indexes
-  foreach(type index query)
-    add_library("test_${type}ing_plugin" SHARED "test_${type}ing_plugin.c")
-    add_dependencies("test_${type}ing_plugin" install_dependencies)
-  endforeach()
+# install the server
+sudo installer -verbose -pkg "${server}" -target /
 
-  if (DARWIN)
-    # Apple needs to be told to explicitly not try to resolve symbols at compile time when
-    # building the plugin. (They will be resolved dynamically when the plugin is dlopen()ed).
-    foreach(type index query)
-      target_link_libraries("test_${type}ing_plugin" -Wl,-undefined -Wl,dynamic_lookup)
-    endforeach()
-  elseif(CYGWIN)
-    # Cygwin needs to use an "import library" (reference: https://cygwin.com/cygwin-ug-net/dll.html)
-    # to get the symbol definitions it uses from gufi_dir2index.
-    target_link_libraries(test_indexing_plugin gufi_dir2index)
-    target_link_libraries(test_querying_plugin gufi_query)
-  else()
-    foreach(type index query)
-      target_link_libraries("test_${type}ing_plugin" "${DEP_INSTALL_PREFIX}/sqlite3/lib/libsqlite3.${EXT}")
-    endforeach()
-  endif()
+# set up environment
+INSTALL_PREFIX="@CPACK_PACKAGING_INSTALL_PREFIX@"
+export PATH="${INSTALL_PREFIX}/bin:${PATH}"
+export DYLD_LIBRARY_PATH="${INSTALL_PREFIX}/lib:${DYLD_LIBRARY_PATH}"
+export PYTHONPATH="${INSTALL_PREFIX}/lib:${PYTHONPATH}"
 
-  add_subdirectory(regression)
-endif()
+# GitHub macOS runner does not run as root, so test_install.sh would fail on copy
+sudo cp "$(dirname @SERVER_CONFIG@)/server.example" "@SERVER_CONFIG@"
 
-# add unit tests
-add_subdirectory(unit)
+"@CMAKE_BINARY_DIR@/contrib/test_install.sh" "${INSTALL_PREFIX}" "@SERVER_CONFIG@" 2>&1
